yarnPath: .yarn/releases/yarn-3.2.1.cjs
enableScripts: false
enableStrictSsl: false
npmAlwaysAuth: true
npmRegistryServer: "https://krogertechnology.jfrog.io/artifactory/api/npm/npm-repo/"
pnpMode: "loose"
nodeLinker: "pnp"
packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  "@kroger/kap-constants@*":
    dependencies:
      typescript: "*"

